Refactor Event Card
rolling-scopes/site pull request #209
Opened 2024-05-15 16:57 UTC by ansivgit

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description
- Add classnames library and transfer to css-module;
- Minor change in markup (classes names);
- Change styles - card height doesn't depend on it's content now;
- Remove unused styles;

## Related Tickets & Documents

- Related Issue #49 
- Closes #126 

## Screenshots, Recordings

Before
![image](https://github.com/rolling-scopes/site/assets/56927722/03995ec4-826b-4da4-b6ea-a473ef9a38a2)

After
![image](https://github.com/rolling-scopes/site/assets/56927722/839a69de-3e43-45b8-b702-cb1840589a5e)

## Added/updated tests?

- [x] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

2024-05-15 17:37 UTC, ramzes-84 requested changes

2024-05-15 17:37 UTC, ramzes-84 commented on src/app/components/event-card/event-card.tsx
> +    <div className={cx('event-card')}>
Shouldn't we use semantic tags?

2024-05-15 17:37 UTC, ramzes-84 commented on src/app/components/event-card/event-card.tsx
> +      <section className={cx('event-card__info')}>
Do we use BEM in project? Just for clarification.

2024-05-17 06:47 UTC, Quiddlee commented
The gap is missing between cards

### before:
![image](https://github.com/rolling-scopes/site/assets/114234698/edcba344-b8f4-4c60-ace7-a7ccda58a421)

### after:
![image](https://github.com/rolling-scopes/site/assets/114234698/d2c5e7b9-201a-474d-9a3b-e57a1dd94975)

2024-05-17 11:13 UTC, ansivgit commented
> The gap is missing between cards
> 
> ### main branch:
> ![image](https://private-user-images.githubusercontent.com/114234698/331491346-edcba344-b8f4-4c60-ace7-a7ccda58a421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NDQzMjMsIm5iZiI6MTcxNTk0NDAyMywicGF0aCI6Ii8xMTQyMzQ2OTgvMzMxNDkxMzQ2LWVkY2JhMzQ0LWI4ZjQtNGM2MC1hY2U3LWE3Y2NkYTU4YTQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxMTA3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDc3NjY2NjllN2QzMWNhNjliODc3MDIxOTJjMjdiZGE0YjU0YzcxMTNjNTg3NjA5YTE3Y2ZiODc5ZmRhNWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ClcF4vMKf88LdCnYHVipY8fNEAfK0qBadyXh7AMd6vw)
> 
> ### your branch:
> ![image](https://private-user-images.githubusercontent.com/114234698/331491049-d2c5e7b9-201a-474d-9a3b-e57a1dd94975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NDQzMjMsIm5iZiI6MTcxNTk0NDAyMywicGF0aCI6Ii8xMTQyMzQ2OTgvMzMxNDkxMDQ5LWQyYzVlN2I5LTIwMWEtNDc0ZC05YTNiLWU1N2ExZGQ5NDk3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxMTA3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2M4M2VjYTQ5MTdhZmFhZjkzZjNhODBkY2JmY2UxMjExODAzOTUwNDNmNTg1NTQ0ZDE5ODlkZmM5NjIxM2Q2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Wx1ydyplQDdx6O34nJGwHQZUHa4P14NI-I1TL7Crq8)

2024-05-17 15:01 UTC, ramzes-84 approved these changes

2024-05-17 19:08 UTC, Quiddlee approved these changes

2024-05-19 12:00 UTC, andron13 approved these changes

2024-05-19 17:10 UTC, natanchik commented on src/features/home/events/events.scss
>      flex-direction: row;
Let's remove this

2024-05-19 17:10 UTC, natanchik commented on src/features/home/events/events.scss
>        flex-direction: row;
And this

2024-05-20 08:02 UTC, ansivgit commented on src/app/components/event-card/event-card.module.scss
> +    position: relative;
We're couldn't as we have the shadow-block with `position: absolute`

2024-05-20 08:26 UTC, natanchik approved these changes

2024-05-20 08:26 UTC, natanchik commented on src/app/components/event-card/event-card.module.scss
> +    position: relative;
ok

2024-05-22 11:26 UTC, merged