Fix: other courses
rolling-scopes/site pull request #50
Opened 2024-04-12 12:36 UTC by Illia-Sakharau

## What type of PR is this? (select all that apply)

- [x] 🐛 Bug Fix

## Description
- [x]  return nearest course to Other courses
- [x] change section title from "Other curses" to "Upcoming courses"

## Related Tickets & Documents

- Closes #44 
- Closes #48 

## Screenshots, Recordings
<img width="1214" alt="Screenshot 2024-04-12 at 16 31 08" src="https://github.com/rolling-scopes/site/assets/124388500/d5c99772-914b-4051-a89c-ea9a1ac4405a">

## Added/updated tests?

- [ ] 👌 Yes
- [x] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

2024-04-14 13:14 UTC, andron13 requested changes
1. The component seems quite large and does quite a few tasks. You might want to consider breaking it down into smaller components, for instance, CourseList and CourseItem.
2. I have to say, I found **courses as Course[]** to be less than ideal.
3. What's going to happen if the data array turns out to be empty?
4. We seem to be parsing the date twice over here. Is there a way we could avoid this duplicate use of `Date.parse`?

2024-04-16 13:04 UTC, Illia-Sakharau commented
1. Removed all unnecessary items from the component.
2. Replaced with a data type check.
3. Added the processing of this case (empty data array).
4. This is not a duplicate of `Date.parse`, I will convert the two values being compared.

2024-04-16 13:16 UTC, andron13 commented on src/app/hooks/use-nearest-course/utils/choose-nearest-course.ts
> +    const bufferPeriodMs = bufferPeriod * 24 * 60 * 60 * 1000;
А зачем переменные создавать в проверке условия?

2024-04-16 13:18 UTC, andron13 commented on src/app/hooks/use-nearest-course/utils/define-prev-next.ts
> +    }
я не смог это прочитать.

2024-04-16 13:22 UTC, andron13 commented on src/features/courses/courses/courses.tsx
> +                  startDate={ nearestCourseStartDate <= Date.parse(course.startDate) ? course.startDate : '(TBD)' }
я не приму в рендере расчёты.

2024-04-17 08:22 UTC, Illia-Sakharau commented on src/app/hooks/use-nearest-course/utils/choose-nearest-course.ts
> +    const bufferPeriodMs = bufferPeriod * 24 * 60 * 60 * 1000;
Изменил

2024-04-17 08:37 UTC, Illia-Sakharau commented on src/features/courses/courses/courses.tsx
> +                  startDate={ nearestCourseStartDate <= Date.parse(course.startDate) ? course.startDate : '(TBD)' }
убрал расчеты из рендера

2024-04-17 08:48 UTC, Illia-Sakharau commented on src/app/hooks/use-nearest-course/utils/define-prev-next.ts
> +    }
Рефакторинг запланирован в таске [#85](https://github.com/rolling-scopes/site/issues/85)

2024-04-17 09:04 UTC, dzmitry-varabei approved these changes

2024-04-17 10:06 UTC, natanchik approved these changes

2024-04-17 10:07 UTC, merged